# -*- coding: utf-8 -*-
"""weather agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fFWUvOQt6KUC03iBTXRI7QY8fWNwWqzI
"""

import requests 

def get_weather(city="Hyderabad", api_key=None):
    if not api_key:
        return "Error: API key not provided. Please provide a valid OpenWeatherMap API key."

    url = f"http://api.openweathermap.org/data/2.5/weather?q={city}&appid={api_key}"
    print(f"Requesting weather data from {url}")

    try:
        response = requests.get(url)
        if response.status_code == 200:
            data = response.json()
            temp = data['main']['temp']
            wind_speed = data['wind']['speed']
            description = data['weather'][0]['description'].capitalize()  

            return (
                f"Weather in {city}:\n"
                f"Temperature: {temp}K\n"
                f"Wind Speed: {wind_speed} m/s\n"
                f"Description: {description}"
            )

        elif response.status_code == 404:
            return f"Error: City '{city}' not found."
        else:
            return f"Error: Unable to fetch weather data. Status code: {response.status_code}"

    except requests.exceptions.RequestException as e:
        return f"An error occurred: {e}"

if __name__ == "__main__":
    API_KEY = "1c3678986ba05c7ca5cea5a983d317ca"  
    city = input("Enter the city name: ")
    if not city:
        city = "Hyderabad"
    print(get_weather(city, API_KEY))

